### ISSUE TITLE
A large number of POLLs are missing

### ISSUE THREAD

**Issue by ChrisTimperley** [ChrisTimperley/cb-multios#8]

**Comment by ChrisTimperley** [comment]
```
root@b3179abdf85e:/challenge# ./test.sh ASCII_Content_Server p100
/challenge/tools /challenge
# /usr/bin/python (stderr): 'Traceback (most recent call last):'
# /usr/bin/python (stderr): '  File "./cb-replay.py", line 1400, in <module>'
# /usr/bin/python (stderr): '    exit(main())'
# /usr/bin/python (stderr): '  File "./cb-replay.py", line 1349, in main'
# /usr/bin/python (stderr): "    with open(pov_filename, 'rb') as pov_fh:"
# /usr/bin/python (stderr): "IOError: [Errno 2] No such file or directory: '/challenge/challenges/ASCII_Content_Server/poller/for-release/GEN_00000_00100.xml'"
# /usr/bin/python (stderr): ''
Traceback (most recent call last):
  File "cb-test.py", line 790, in <module>
    exit(main())
  File "cb-test.py", line 781, in main
    ret = runner.run()
  File "cb-test.py", line 640, in run
    passed_tests += self.check_result(replay_result, xml_list)
  File "cb-test.py", line 585, in check_result
    xml_replay_stdout = replay_stdout.split(xml, 1)[1]
IndexError: list index out of range
FAIL: 100
```

**Comment by ChrisTimperley** [comment]
From inspecting `genpolls.sh`, it looks like the polls aren't missing, but rather that we generating 100 POLLs and using a zero-based index to number them.
